#!/bin/bash
# init.sh - Development server startup script
# Generated by dev-agent-harness

set -e

echo "🚀 Starting development environment..."

# Install dependencies
echo "📥 Installing dependencies..."
npm install

# Start development server on port 5173
echo "🌐 Starting development server on port 5173..."
npm run dev
